services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Aa123456
      POSTGRES_DB: github-email-notifier-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d github-email-notifier-db"]
      interval: 2s
      timeout: 2s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 5

  api:
    build: .
    ports:
      - "4200:4200"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://user:Aa123456@db:5432/github-email-notifier-db?schema=public"
      REDIS_URL: "redis://redis:6379"

  tunnel:
    image: cloudflare/cloudflared
    restart: always
    command: tunnel run --token ${CLOUDFLARE_TUNNEL_TOKEN}

volumes:
  postgres_data: